#!/bin/sh

# FAIRBOT script to create SQL for playing Fairwinds
#
# Copyright 2015, Berend M. Tober
#

me=$(basename $0)
tmp=".${me}.$$"
touch "${tmp}"
trap 'rm "${tmp}"' EXIT
export COLUMNS=10
unset file


syntax="
NAME
  ${me} - Interactive menu for the Fairwinds game. 

SYNOPSIS
  ${me} [options] host [username]  

DESCRIPTION
  ${me} is a script that presents an interactive menu system
  for playing the Fairwinds game hosted on the specified host.
  It requires that the psql data base client software be
  installed and accessible in the user's PATH.

  If no username is specified, it defaults to the current user.

  CTRL-D is used to exit menus.

OPTIONS

  -h
      Show help menu.

  -f file
      Save generated SQL statements to file instead of executing them.

"

if [ $# -lt 1 ]
then
  echo "${syntax}"
  exit
fi

while [ "$#" -gt 0 ]
do
  case $1 in
    -\?|-h)
      shift
      syntax
      exit
      ;;
    -f)
      file="${2}"
      shift 2
      ;;
    -*)
      echo "invalid option '${1}'"
      exit 1
      ;;
    *)
      break
      ;;
  esac
done

fairian_name="${2-$USER}"
export PGDATABASE="fairwinds"
export PGHOST="${1}"
export PGUSER="${fairian_name}"

display_game_info="select click, start_time, end_time, click_interval from fairwinds;"
display_connections="select * from connection;"
display_players="select  fairian_name, email_address, created_date, click_order_count, click_select_count from fairian order by fairian_name;"
display_health_journal="select click, fairian_name, debit, credit, balance, description from health_journal where fairian_name = current_user order by click, seq;"
display_cash_journal="select click, fairian_name, debit, credit, balance, description from cash_journal where fairian_name = current_user order by click, seq;"
display_food_journal="select * from food_journal where fairian_name = current_user order by click;"
display_bonds="select * from bond where bond_owner = current_user or bond_issuer = current_user;"
display_land="select * from land where fairian_name = current_user;"
display_contracts="select * from work where customer = current_user or supplier = current_user;"
display_notes="select * from note where factor = current_user or debtor = current_user;"


function executesql {
  if [[ -n "${file}" ]] 
  then
    echo "${sql}" >> "${file}"
  else
    sql="\set VERBOSITY terse
        ${1}"
    psql -q <<< "${sql}"
  fi
}

function createmenu {
  echo "Creating Fairian '${fairian_name}'"
  read -p "Player email address=" email

  sql="insert into fairian (fairian_name, passwd, email_address) values ('${fairian_name}', '${PGPASSWORD}', '${email}');"
  prompt="insert into fairian (fairian_name, passwd, email_address) values ('${fairian_name}', '******', '${email}');"
  export PGUSER="fairwinds"
  executesql "${sql}" "${prompt}"
  export PGUSER="${fairian_name}"
}

function labormenu {
  land_plots=$(psql -q -A -t <<< "select serial_number from land where fairian_name = current_user order by 1;")
  skills=$(psql -q -A -t <<< "select skill_name from skill order by 1 limit 1;")

  unset fields values
  local OLDPS3="${PS3}"
  PS3="Select skill name "
  select skill_name in ${skills}
  do
    if [[ -n "${skill_name}" ]]
    then
      fields="${fields}, skill_name"
      values="${values}, '${skill_name}'"
    fi
    break
  done

  PS3="Select work place serial number "
  select work_place in ${land_plots}
  do
    if [[ -n "${work_place}" ]]
    then
      fields="${fields}, work_place"
      values="${values}, '${work_place}'"
    fi
    break
  done
  PS3="${OLDPS3}"

  fields="${fields#,}"
  values="${values#,}"
  sql="insert into work (${fields}) values (${values});"
  executesql "${sql}"
}

function callmenu {
  notes=$(psql -q -A -t <<< "select serial_number from note where factor = current_user order by 1;")

  unset fields values
  local OLDPS3="${PS3}"
  PS3="Select note serial number "
  select note in ${notes}
  do
    [[ -z "${note}" ]] && break
    sql="update note set called = true where serial_number = '${note}';"
    executesql "${sql}"
    break
  done
  PS3="${OLDPS3}"
}

function resignmenu {
  supplier_contracts=$(psql -q -A -t <<< "select contract_number from work where customer = current_user or supplier = current_user order by 1;")

  local OLDPS3="${PS3}"
  PS3="Select labor contract number "
  select contract_number in ${supplier_contracts}
  do
    [[ -z "${contract_number}" ]] && break
    sql="update work set active = false where contract_number = '${contract_number}';"
    executesql "${sql}"
    break
  done
  PS3="${OLDPS3}"
}

function optionsmenu {
  case "${1}" in
    bond)
      read -p "bond term=" term
      if [[ -n "${term}" ]]
      then
        fields="${fields}, term"
        values="${values}, ${term}"
      fi
      ;;
    land)
      case "${2}" in
        bid)
          read -p "land productivity=" productivity
          if [[ -n "${productivity}" ]]
          then
            fields="${fields}, productivity"
            values="${values}, ${productivity}"
          fi
          ;;
        ask)
          read -p "land serial number=" serial_number
          if [[ -n "${serial_number}" ]]
          then
            fields="${fields}, serial_number"
            values="${values}, '${serial_number}'"
          fi
          ;;
      esac
      ;;
    work)
        read -p "contract term=" term
        if [[ -n "${term}" ]]
        then
          fields="${fields}, term"
          values="${values}, ${term}"
        fi
        
      case "${2}" in
        bid)
          read -p "minimum effectiveness=" effectiveness
          if [[ -n "${effectiveness}" ]]
          then
            fields="${fields}, effectiveness"
            values="${values}, ${effectiveness}"
          fi

          read -p "work place serial number=" work_place
          if [[ -n "${work_place}" ]]
          then
            fields="${fields}, work_place"
            values="${values}, '${work_place}'"
          fi
          ;;
      esac

      fields="${fields}, skill_name"
      values="${values}, 'farmer'"
      ;;
    food)
      read -p "quantity=" quantity
      if [[ -n "${quantity}" ]]
      then
        fields="${fields}, quantity"
        values="${values}, ${quantity}"
      fi
      ;;
    note)
      notes=$(psql -q -A -t <<< "select serial_number from note order by 1;")
      local OLDPS3="${PS3}"
      PS3="Select note serial number "
      select serial_number in ${notes}
      do
        fields="${fields}, serial_number"
        values="${values}, '${serial_number}'"
        break
      done
      PS3="${OLDPS3}"
      ;;
  esac
    
  if [[ -z "${fields}" ]]
  then
    sql="insert into ${mrkt}_${side% - *} default values;"
  else
    sql="insert into ${mrkt}_${side% - *} (${fields##,}) values (${values##,});"
  fi
  executesql "${sql}"
}


function sidemenu {
  sides=(
      "bid - Buy order" 
      "ask - Sell order"
      )
  unset side
  local OLDPS3="${PS3}"
  PS3="${mrkt} buy or sell? "
  select side in "${sides[@]}"
  do
    side="${side%%[[:space:]]*- *}"
    case "${side% - *}" in
      "bid"|"ask")
        read -p "expiration=" expiration
        if [[ -n "${expiration}" ]]
        then
          fields="expiration"
          values="${expiration}"
        else
          fields=""
        fi

        read -p "${side} price=" price
        if [[ -n "${price}" ]]
        then
          fields="${fields}, price"
          values="${values}, ${price}"
        fi
        ;;
    esac
    break
  done
  PS3="${OLDPS3}"
}

function marketmenu {
  mrkts=("bond" "land" "work" "food" "note")
  unset mrkt
  local OLDPS3="${PS3}"
  PS3="Select market "
  select mrkt in "${mrkts[@]}"
  do
    case "${mrkt}" in
      "bond"|"land"|"work"|"food"|"note")
        sidemenu
        ;;
    esac
    break
  done

  [[ -n "${mrkt}" ]] && [[ -n "${side}" ]] && optionsmenu ${mrkt} ${side}
  PS3="${OLDPS3}"
}

function reportsmenu {
  options=(
      "Game         - Display game information" 
      "Connections  - Display currently logged in players" 
      "Players      - Display registered players" 
      "Health       - Display health history journal"
      "Cash         - Display cash transcation journal"
      "Food         - Display food transcation journal"
      "Land         - Display owned land plots"
      "Bonds        - Display owned and issued bonds"
      "Contracts    - Display engaged labor contracts"
      "Notes        - Display factor/debtor notes")
  local OLDPS3="${PS3}"
  PS3="Select report "
  unset option
  select option in "${options[@]}"
  do
    option="${option%%[[:space:]]*- *}"

    case "${option}" in
      Game)
        sql="
        \C 'Game Information'
        ${display_game_info}
        \C
        "
        executesql "${sql}" "${display_game_info}"
        ;;
      Connections)
        sql="
        \C 'Connections'
        ${display_connections}
        \C
        "
        executesql "${sql}" "${display_game_info}"
        ;;
      Players)
        sql="
        \C 'Fairians'
        ${display_players}
        \C
        "
        executesql "${sql}" "${display_game_info}"
        ;;
      Health)
        sql="
        \C 'Recent Health Journal Entries'
        ${display_health_journal}
        \C
        "
        executesql "${sql}" "${display_health_journal}"
        ;;
      Cash)
        sql="
        \C 'Recent Cash Journal Entries'
        ${display_cash_journal}
        \C
        "
        executesql "${sql}" "${display_cash_journal}"
        ;;
      Food)
        sql="
        \C 'Recent Food Journal Entries'
        ${display_food_journal}
        \C
        "
        executesql "${sql}" "${display_food_journal}"
        ;;
      Land)
        sql="
        \C 'Land'
        ${display_land}
        \C
        "
        executesql "${sql}" "${display_land}"
        ;;
      Bonds)
        sql="
        \C 'Bonds'
        ${display_bonds}
        \C
        "
        executesql "${sql}" "${display_bonds}"
        ;;
      Contracts)
        sql="
        \C 'Labor Contracts'
        ${display_contracts}
        \C
        "
        executesql "${sql}" "${display_contracts}"
        ;;
      Notes)
        sql="
        \C 'Notes'
        ${display_notes}
        \C
        "
        executesql "${sql}" "${display_notes}"
        ;;
      esac
  done
  PS3="${OLDPS3}"
}

function mainmenu {
  options=(
      "Create     - Create a Fairian account named ${fairian_name}" 
      "Reports    - Display game data"
      "Trade      - Enter buy/sell orders" 
      "Labor      - Assign self-owned labor contract" 
      "Terminate  - End a labor contract" 
      "Call       - Demand note payment" 
      )
  PS3="Main menu selection "
  unset option
  select option in "${options[@]}"
  do
    option="${option%%[[:space:]]*- *}"

    case "${option}" in
      "Create")
        createmenu
        ;;
      "Reports")
        reportsmenu
        ;;
      "Trade")
        marketmenu
        ;;
      "Labor")
        labormenu
        ;;
      "Terminate")
        resignmenu
        ;;
      "Call")
        callmenu
        ;;
      *)
        break 
        ;;
    esac
  done
  unset PS3
}

[[ -z "${PGPASSWORD}" ]] && read -s -p "Fairwinds password:" PGPASSWORD
echo
export PGPASSWORD
mainmenu


