= Fairwinds Interactive Menu Tutorial
:author:    Berend Tober <btober@computer.org>
:copyright: 2015, Berend Tober
///////////////////////////
:backend:   slidy
///////////////////////////
:toc:
:max-width: 45em
:data-uri:
:icons:
:date: 17-Dec-2015

== Fairwinds Game Tutorial 0 - What is Fairwinds

* Multi-Player On-Line Game Simulating Five Double-Auction Markets

* Interactive Menu Interface

A successful player will utilize all five markets in order to
improve their rank in the standings relative to other players. 

A sample of the standings report is shown in the table below in
which the first column lists the Fairian name, and players are
ranked according to health and wealth, as appear in the second
and third columns. 


--------------------------------------------
                       Fairwinds Tournament Standings
 fairian_name | health | wealth  |  cash   |  food  | bonds | land  | notes 
--------------+--------+---------+---------+--------+-------+-------+-------
 bob          | 0.9942 |   5.042 |   0.000 | 34.508 | 0.000 | 0.534 |   -30
 david        | 0.9923 |  57.580 |  45.000 | 12.580 | 0.000 | 0.000 |     0
 cathy        | 0.9895 |  86.089 |  69.000 | 17.089 | 0.000 | 0.000 |     0
 edwin        | 0.9884 |  29.253 |  12.000 | 17.253 | 0.000 | 0.000 |     0
 fredrick     | 0.9884 |  27.253 |  10.000 | 17.253 | 0.000 | 0.000 |     0
 gina         | 0.9884 |  26.411 |  14.000 | 12.411 | 0.000 | 0.000 |     0
 hendrik      | 0.9884 |  25.253 |   8.000 | 17.253 | 0.000 | 0.000 |     0
 ingrid       | 0.9884 |  24.253 |   7.000 | 17.253 | 0.000 | 0.000 |     0
 james        | 0.9884 |  23.253 |   6.000 | 17.253 | 0.000 | 0.000 |     0
 karen        | 0.9884 |  22.253 |   5.000 | 17.253 | 0.000 | 0.000 |     0
 leonard      | 0.9884 |  21.253 |   4.000 | 17.253 | 0.000 | 0.000 |     0
 norman       | 0.9874 |  20.253 |   3.000 | 17.253 | 0.000 | 0.000 |     0
 michelle     | 0.9874 |  20.253 |   3.000 | 17.253 | 0.000 | 0.000 |     0
 olivia       | 0.9874 |  19.253 |   2.000 | 17.253 | 0.000 | 0.000 |     0
 peter        | 0.9874 |  18.253 |   1.000 | 17.253 | 0.000 | 0.000 |     0
--------------------------------------------

There is a lot going behind this ranking table, but generally
speaking, the flow of the game is driven by the standings
ranking since sustaining health requires food, food is
produced by cultivating land, land is acquired using capital,
and capital is raised through financing and assumption of debt.

While the following tutorials will help with understanding,
one thing to note here is that no matter what level of
total wealth, health always dominates as a ranking criteria,
so Cathy, who ranks the highest wealth, is third behind Bob and
David since the latter two have higher health percentage values.

As will be demonstrated subsequently, achieving and maintaining
perfect 100% health is expected to be realizable by multiple
players and so as the game progresses most likely wealth will
be the discriminating ranking factor.

Therefore, it pays to remain cognizant of the balance between the
separate wealth components, as listed in the remaining table
columns, as the worth of food and land will vary according to
fluctuating market values for those assets.


== Fairwinds Game Tutorial 1 - Basic Requirements: Client Software

This tutorial demonstrates using the free interactive menu user 
interface to play Fairwinds. 

Playing 'Fairwinds' requires that your computer establish a connection
to the game utilizing  with the free +psql+ client software application
and the +fairbot+ interactive menu script. 

As you make menu selections with the +fairbot+ script, the  script
will construct apropriate structured query language (SQL) commands and
send them to the game by using the +psql+ client software
automatically.

=== Obtaining PSQL Client Software


==== PSQL on Linux

The +psql+ client is part of the +postgresql+ package. On Linux this is
installed with 

--------------------------------------------
yum install postgresql
--------------------------------------------

==== PSQL on Windows

On Windows systems, +postgresql+ is available through the 'Cygwin' software
tools package. Visit the Cygwin web site https://www.cygwin.com/ to download
and install 'Cygwin'. During the installation, be sure to select the
+postgresql+ package.

After installing Cygwin, double-click the Cygwin icon. This will open a local
terminal window, and at this point the instructions are the same as for running
+psql+ on Linux.

=== PSQL Configuration

The 'Fairwinds' game communicates certain error conditions by means of
interally raising execptions and emitting an associated, explanatory
error message. In the default configuration, +psql+ emits additional
contextual information which, while helpful to an administrative
operator, may obscure the essential error message for a typical player.

The verbosity of these outputs can be reduced with a configuration
setting. If you are already running the +psql+ client, then you should
run the following command at the +psql+ prompt:

--------------------------------------------
\set VERBOSITY terse
--------------------------------------------

Alternatively, you can easily create or modify the +psql+ client
resource configuration file by copy-and-pasting the following command
at the shell command prompt:

--------------------------------------------
echo "\set VERBOSITY terse" >> ~/.psqlrc
--------------------------------------------

=== Obtaining the Interactive Menu Script

The +fairbot+ menu application is a Bash shell script that runs from
the Linux command line. You can download the +fairbot+ menu script
from

 https://github.com/bmtober/fairwinds

After downloading, make sure the script is executable with 

--------------------------------------------
 chmod +x fairbot
--------------------------------------------

=== Invoking the Interactive Menu

Runing the +fairbot+ script at the Linux command line with no 
parameters displays a simple usage and help menu:


--------------------------------------------
./fairbot


NAME
  fairbot - Interactive menu for the Fairwinds game. 

SYNOPSIS
  fairbot [options] host [username]  

DESCRIPTION
  fairbot is a script that presents an interactive menu system
  for playing the Fairwinds game hosted on the specified host.
  It requires that the psql data base client software
  be installed and accessible in the user's PATH.
   
  If no username is specified, it defaults to the current user.

  CTRL-D is used to exit menus.

OPTIONS

  -h
      Show help menu.

  -f file
      Save generated SQL statements to file instead of executing them.

--------------------------------------------

The above explains that you must specify the hostname (or IP
address) of the game, and optionally specify a username.

By specifying an output file with the +-f+ option, you can
create a file showing the SQL commands that would have been
run. This file can then be studied and modified, and then if
you develop facility with utilizing the +psql+ client directly,
you could then run the file as a command script.



== Fairwinds Game Tutorial 2 - Creating a user account

To start the interactive menu, run the +fairbot+ script
specifying the host name and a username alias, for example

--------------------------------------------
$ ./fairbot localhost alice
Fairwinds password:
--------------------------------------------

In this case the game is running on the localhost, but generally
you will specify a fully-qualified host name or IP address. If
you omit the username, then it defaults to the current system
login name.

The script immediately prompts for a password. The password
characters you type are not echoed on the display.  If this is
the first time you are playing, then this username and password
will become the credentials you login with in future evolutions.
The username will be your 'Fairian' name.

The main menu and a short description of each menu item function
is displayed. You select a menu item by entering the number
displayed on the left for each item.

--------------------------------------------
1) Create     - Create a Fairian account named alice
2) Reports    - Display game data
3) Trade      - Enter buy/sell orders
4) Labor      - Assign self-owned labor contract
5) Terminate  - End a labor contract
6) Call       - Demand note payment
Main menu selection 
--------------------------------------------

Alice enters option #1 to create her account, which leads to
a prompt for an email address. Entering a valid email address
is useful if you want to receive important game updates from
time to time as they may be released. Player information is
generally not shared with other organizations.


--------------------------------------------
Main menu selection 1
Creating Fairian 'alice'
Player email address=alice@example.com
#?
--------------------------------------------

By default, when the menu system returns control it is back
up one menu level, and the menu is not re-displayed.  If you
simply press the +ENTER+ key, the current level menu will be
displayed, showing that after creating the Fairian account
the menu system returned to the top level.


--------------------------------------------
1) Create     - Create a Fairian account named alice
2) Reports    - Display game data
3) Trade      - Enter buy/sell orders
4) Labor      - Assign self-owned labor contract
5) Terminate  - End a labor contract
6) Call       - Demand note payment
Main menu selection  
--------------------------------------------

Option #2 displays a list of reports that can be used to learn
information about the game and markets. All this information
is updated automatically and also displayed on the game web
site periodically, but these reports allow you to view the
most current information. Note, however, that there are fees
assessed for excessive queries during each click, so you should
be judicious.


--------------------------------------------
 1) Game         - Display game information
 2) Connections  - Display currently logged in players
 3) Players      - Display registered players
 4) Health       - Display health history journal
 5) Cash         - Display cash transcation journal
 6) Food         - Display food transcation journal
 7) Land         - Display owned land plots
 8) Bonds        - Display owned and issued bonds
 9) Contracts    - Display engaged labor contracts
10) Notes        - Display factor/debtor notes
Select report 1
--------------------------------------------

The Game report lists a short report showing the current click,
which is a measure of advancing game time, a real-world start
and end time, if specified, for the game, and the real-world
duration in seconds of each click. The latter determines how
quickly the game advances as well as the frequency of updated
display of game information on the web site.


--------------------------------------------
                Game Information
click | start_time | end_time | click_interval 
-------+------------+----------+----------------
    1 |            |          |             20
(1 row)
--------------------------------------------

The Connections report lists the current game connections. Note
that this report is updated once each click, so it will always
be a little out of date.

The Players report lists the registered players, whether
currently active or not.  Her new account is the only registered
player, since in this tutorial exposition she is, in fact,
the first player to enter the game.


--------------------------------------------
                                             Fairians
 fairian_name |   email_address   |        created_date        | click_order_count | click_select_count 
--------------+-------------------+----------------------------+-------------------+--------------------
 alice        | alice@example.com | 2015-12-15 20:23:29.893926 |                 0 |                  1
(1 row)

#?
--------------------------------------------

The +click_order_count+ and the +click_select_count+ keep track
of how many trade orders and select queries, respectively,
each 'Fairian' has executed during the current click. While
there is a threshold level of free activity, and the two
counter values reset to zero at the beginning of each click,
subsequent tutorials discuss the fee accessed to discourage
excessive trade and query activity.

The Health report lists the health journal, that is, the
history of changes to 'Fairian' health.  The first row shows
the initially-assigned 100% health value.  The 'Fairwinds'
game assigns new players a health value equal to the lowest
health value of all other players, i.e., as tied with the
last-place player.

--------------------------------------------
Select report 4
                     Recent Health Journal Entries
 click | fairian_name | debit |  credit  | balance  |                           description                           
-------+--------------+-------+----------+----------+-----------------------------------------------------------------
     1 | alice        |     1 |          |        1 | Initial health
     2 | alice        |       | 0.019635 | 0.980365 | health deterioration based on insufficient sustenance balance 0
     3 | alice        |       |  0.01925 | 0.961115 | health deterioration based on insufficient sustenance balance 0
(3 rows)

--------------------------------------------

When there are no other players to compare to, as is the case
for the first player to join, this initial value is set to
100%. Without further action to sustain health, 'Fairian'
health deteriorates as game time advances, as shown for
click 2 and 3.

The Cash report similarly presents a journal, or history,
of activity, showing the initial state of poverty.

--------------------------------------------
Select report 5
                              Recent Cash Journal Entries
 click | fairian_name | account | debit | credit | balance |     description      
-------+--------------+---------+-------+--------+---------+----------------------
     1 | alice        | cash    |     0 |      0 |       0 | Initial cash balance
(1 row)
--------------------------------------------


Some of the other report menu items will be illustrated in
later tutorials.


== Fairwinds Game Tutorial 3 - Trade Menu

The 'Trade' menu option on the main menu allows entry to
trading activity on the five markets: finance (+bond+), real
estate (+land+), labor (+work+), commodity (+food+), and debt
(+note+).

--------------------------------------------
Main menu selection 3
1) bond
2) land
3) work
4) food
5) note
Select market
--------------------------------------------

A brief description of each is given below:


=== Instruments of Trade


[horizontal] 
*+bond+*:: The finance market.  Literally a 'bond' is just
that, a promise (as in "my word is my bond") to re-pay a fixed
amount of money at some specified future time. It represents
a contract between two 'Fairians' or between a 'Fairian' and
the governing market authority (which you can think of as "the
government"). From the bond buyer's (the lender) perspective,
bonds are guaranteed investments: regardless of the issuer's
(the borrower) ability to repay, the governing market will
create enough money to cover any shortfall and repay the full
face amount at maturity.

*+land+*:: The real estate market. Plots of land which have been
intially surveyed (note that "surveyed" is merely a notional
term in this context meaning only "created by the game")
are offered for sale. If a land plot has been purchased by a
'Fairian', the this market can be used for re-sale.

*+work+*:: The labor market. Similar to a +bond+, a labor
contract represents an agreement between 'Fairians'. Labor
contracts specify that one 'Fairian' will work for another
for at least a specified amount of time. Labor contracts are
created when buyers, bidding to hire, and sellers, asking to
work, offer mutually compatible terms with respect to time,
skill, effectiveness, and payment.

*+food+*:: The commodity market allows 'Fairians' to buy and
sell food.

*+note+*:: The debt market. If a bond issuing 'Fairian' does
not have sufficient cash on hand to repay at bond maturity,
then a +note+ is written listing the borrower as a debtor,
and that +note+ is then factored at discount on the debt market.

After selecting any one of these markets, you will prompted
for which 'side' of the trade you want to place an order on.

--------------------------------------------
1) bid - Buy order
2) ask - Sell order
bond buy (bid) or sell (ask)? 
--------------------------------------------

'bid' and 'ask' refer to 'buy' and 'sell'
orders, respectively.

== Fairwinds Game Tutorial 4 - Bootstrapping the Land Market

When 'Fairwinds' is initialized, there are no 'Fairians',
no land, no food, and no money. As players enter the game,
resources must be brought into existence by means of market
activity that creates demand. The market response that creates
the land and money needed for the game to progress is called
"bootstrapping", 'i.e.', the game is figuratively "lifted by
the bootstraps".

This tutorial illustrates the bootstrapping protocol for the
land market and the role you play in making it happen.

For purposes of illustration in this tutorial there is only
a single 'Fairian' participating in the game.  While this
obviously is a circumstance almost all players will not
encounter (since only one player is ever the first player to
enter the game!), the techniques employed are sufficiently
illustrative as to be instructive on how general play proceeds.

Utilizing the interactive menu, Alice connects to 'Fairwinds'
and makes selections to issue a land bid, i.e. a trade
order to buy land.

--------------------------------------------
Main menu selection 3
1) bond
2) land
3) work
4) food
5) note
Select market 2

1) bid - Buy order
2) ask - Sell order
land buy (bid) or sell (ask)? 1
expiration=

--------------------------------------------

At this point, as series of prompts are presented to define
the details of the order. 

--------------------------------------------
land buy (bid) or sell (ask)? 1
expiration=
price=
land productivity=
--------------------------------------------

The first prompt is for +expiration+, which is optional and
defaults to 1.

The expiration value specifies how many clicks the offer will
stand for and at which point, if it has not been executed,
will be deleted.

The +price+ value is also optional: omitting it implies a
'market order', similar to the real-world financial markets
where a market order means "I will match and trade at as good
an offer as any other offer."

+Productivity+ is a measure of land quality and is a value
between zero and one indicating how much food the land can
produce when cultivated -- so more productive land is more
valuable than less productive land. The specified value is
the minimum land productivity value the buyer will accept.
It defaults to zero if not specified.

In this case Alice specifies no value for each entry, thus
implying default values for each. Since there are no existing
land sell orders, the game invokes bootstrapping, which results
in creating a new land plot that is then offered for sale and
listed on the game standings report web site.


--------------------------------------------
                                Land Asks
 serial_number  | expiration | productivity | price | fairian_name | side 
----------------+------------+--------------+-------+--------------+------
 356a192b7913b0 |            |      0.00000 |     0 |              | ask
(1 row)
--------------------------------------------

Note that the +fairian_name+ column is blank, which indicates
that this land plot is being sold by the governing market
authority rather than another 'Fairian', and that there is no
expiration date. This land sell offer will stand open until some
'Fairian' makes an offer.

The +serial_number+ is a unique identifier automatically 
generated by the game.

The ask +price+ for bootstrapped land is determined by a
land-scarcity pricing formula according to a simple quadratic
polynomial. For the very first plot of land, the plot is
offered for sale at zero cost, and subsequent plots are priced
at monotonically-increasing values.

Note that the way bootstrapping works, two orders are
required for Alice to actually purchase the land: one to invoke
bootstrapping, and a second to actually make the purchase. While
apparently cumbersome, bootstrapping works this way as a matter
of fairness. That is, the 'Fairian' invoking bootstrapping
has no special right to take ownership of the land: Any one
can bid competitively for it.  Had there been any open bid
orders, the bootstrap sell order may have matched against,
and executed with, one of those.

But since Alice enjoys the non-competitive situation of being
the sole player, she then places another land bid order with
default values and confirms her acquisition of the land plot
by reviewing the game standing web page

--------------------------------------------
                        Land Plots
 fairian_name | serial_number  | productivity | land_value 
--------------+----------------+--------------+------------
 alice        | 356a192b7913b0 |      0.00000 |      0.000
(1 row)
--------------------------------------------

showing that she is now listed as the owner.

The land_value is set according to the trade execution 
price.

The cash journal report reflects the transaction, even though 
no cash changed hands.

--------------------------------------------
                         Recent Cash Journal Entries
 click | fairian_name | debit | credit | balance |        description         
-------+--------------+-------+--------+---------+----------------------------
     1 | alice        |     0 |      0 |       0 | Initial cash balance
     4 | alice        |       |      0 |       0 | Bought land 356a192b7913b0
(2 rows)
--------------------------------------------

Now that Alice is a land owner, she can cultivate the land to produce
food.


== Fairwinds Game Tutorial 5 - Cultivating Self-Owned Land

'Fairians' require sustenance ('i.e.', food) as the game
advances. Provisioning sufficient sustenance has implications
that will be dicussed more fully in subsequent tutorials,
but suffice it to say for now that food is important, just
like in the real world.

Sustenance is derived from land plots by cultivation (or
'farming'). The activity of cultivation is an example of
skilled labor, and 'Fairwinds' labor activity is executed
under contracts established on the labor market.

Normally, a labor contract is made between two 'Fairians': a
customer (the land-owning buyer of a labor contract bidding to
employ others) and a supplier (the seller of a labor contract
asking to earn 'Faircoin' by working for another 'Fairian').

That more typical, competitive/cooperative arrangement is
the topic of a later tutorial. This tutorial explains how a
'Fairian' can engage in cultivation of their own land.

The self-owned land cultivation scenario is less complicated
than labor contracts between 'Fairians' because the land owner
is both the customer and the supplier, and neither bidding
nor exchange of money is involved: A contract for self-owned
land labor is established directly without using the market
bid/ask process.

From the main menu, the Labor menu selection leads to a prompt
for a skill type (currently 'farming' is the only skill
type), followed by a menu selection of land plots Alice owns.

--------------------------------------------
1) Create     - Create a Fairian account named alice
2) Reports    - Display game data
3) Trade      - Enter buy/sell orders
4) Labor      - Assign self-owned labor contract
5) Terminate  - End a labor contract
6) Call       - Demand note payment
Main menu selection 4

1) farmer
Select skill name 1

1) 356a192b7913b0
Select work place serial number 1
--------------------------------------------

The work place should be specified as the land plot
serial number value corresponding to the land to be
cultivated. The skill name corresponding to land cultivation
is "farmer".

The game standings web site subsequently lists the created
labor contract:

--------------------------------------------
                                           Labor Contracts
   work_place   | skill_name | contract_number | issue_date | term | customer | supplier | labor_rate 
----------------+------------+-----------------+------------+------+----------+----------+------------
 356a192b7913b0 | farmer     | da4b9237bacccd  |          5 |    1 | alice    | alice    |      0.000
(1 row)
--------------------------------------------

The contract_number and issue_date column values are determined
automatically when a labor contract is created. The labor rate
is a derived value of price divided by term.  As mentioned
above, the customer and supplier will both automatially be set
to the land-owning 'Fairian'. The term will be automatically
set to a value of one (which is discussed further below).

The term column specifies the minimum time period committment
(in clicks) that the labor supplier makes to the customer. That
is, while the customer can terminate a labor contract at any
time, the supplier can do so only after the contract term
has expired. For the self-owned land scenario, since the land
owner is both customer and supplier there is no need to limit
the authority to terminate the labor contract, so a value of
one is automatically assigned, and it need not be specified
in the insert statement.

Note, though, that a labor contract does not terminate
automatically upon time advancing beyond the contract term. The
supplier will continue in the activity of cultivation on the
contracted plot of land until one or the other party to the
contract explicitly terminates the contract.  Consequently,
it makes no sense for the self-owned land labor contract
to set the value to anything larger than one, which is the
automatically-assigned value.


== Fairwinds Game Tutorial 6 - Skills Development and the Skill Journal

Once Alice has engaged herself in cultivation of her own plot
of land, there are a few important implications.

The first important implication is that Alice develops
proficiency at a skill, namely, by engaging in cultivation,
she gets better at it.  A record of her developing skill
proficiency is recorded in the skill journal displayed on the
game standings web page and shows the slowly improving skill
balance starting at click 6, when cultivation was initiated.


--------------------------------------------
                                                    Skill Journal
 click | fairian_name | skill_name |  debit  | credit | balance |                    description                     
-------+--------------+------------+---------+--------+---------+----------------------------------------------------
     6 | alice        | farmer     | 0.01732 |        |   0.017 | skill improvement based on contract da4b9237bacccd
     7 | alice        | farmer     | 0.01702 |        |   0.034 | skill improvement based on contract da4b9237bacccd
     8 | alice        | farmer     | 0.01672 |        |   0.051 | skill improvement based on contract da4b9237bacccd
     9 | alice        | farmer     | 0.01643 |        |   0.067 | skill improvement based on contract da4b9237bacccd
    10 | alice        | farmer     | 0.01615 |        |   0.084 | skill improvement based on contract da4b9237bacccd
(5 rows)
--------------------------------------------

As in the real world, proficiency at any skill will improve
with practise and will atrophy with neglect. The rows shown in
this report of the skill journal shows that Alice, engaging
in farming, improved her proficiency by a small, decreasing
amount each click. The growth and atrophy rates for each skill
are small numbers pseudo-randomly fixed when the game starts.

Proficiency will continue to improve so long as she continues as
the supplier to an active labor contract, but the improvement
exhibits 'diminishing returns' since the value approaches
unity and will never exceed 100%.

When the contract is terminated, her proficiency will atrophy
unless she engages as a supplier on a new contract.

Proficiency atrophies at a constant percentage rate (which
thus also exhibits diminishing returns behavior in that the
amount by which proficiency decreases each click continually
itself diminishes).

== Fairwinds Game Tutorial 7 - Cultivation and the Land Journal

The second consequence of Alice engaging in cultivation of
her own land plot is that the land productivity improves.

A record of the land productivity improvement is recorded in
the land journal.

--------------------------------------------
                                                  Land Journal
 click | serial_number  | fairian_name |  debit   |  credit  | balance |              description               
-------+----------------+--------------+----------+----------+---------+----------------------------------------
     3 | 356a192b7913b0 |              | 0.000000 | 0.000000 |   0.000 | Initial land productivity
     6 | 356a192b7913b0 | alice        | 0.000725 |          |   0.001 | land improvement based on cultivation 
     7 | 356a192b7913b0 | alice        | 0.000724 |          |   0.001 | land improvement based on cultivation 
     8 | 356a192b7913b0 | alice        | 0.000724 |          |   0.002 | land improvement based on cultivation 
     9 | 356a192b7913b0 | alice        | 0.000723 |          |   0.003 | land improvement based on cultivation 
    10 | 356a192b7913b0 | alice        | 0.000723 |          |   0.004 | land improvement based on cultivation 
(6 rows)
--------------------------------------------

The rows in this report show the initial zero productivity
at the point of land survey and initial offer for sale,
and then during each click starting once the land came
under cultivation, the land productivity improved by a small
amount. The behavior of land productivity is very similar to
the way skill proficiency changes as a 'Fairian' engages in
activity: when land is cultivated, the productivity improves,
and when left fallow, the productivity diminishes. And in both
cases the amount of change exhibits dimishing returns behavior
as the net balance approaches one or zero, respectively.

Proficiency and productivity together influence the total food
production yield.


== Fairwinds Game Tutorial 8 - Cultivation and the Food Journal

Another important consequence of Alice engaging in cultivation of her
own plot of land is that this activity results in food production.

A record of the fruits of her labor is recorded in the food journal:

--------------------------------------------
                                         Food Journal
 click | fairian_name | debit  | credit | balance |                description                
-------+--------------+--------+--------+---------+-------------------------------------------
     1 | alice        | 0.0000 | 0.0000 |  0.0000 | Initial food balance
     6 | alice        | 1.0000 |        |  1.0000 | total production from land 356a192b7913b0
     6 | alice        |        | 1.0000 |  0.0000 | daily sustenance
     7 | alice        | 1.0000 |        |  1.0000 | total production from land 356a192b7913b0
     7 | alice        |        | 1.0000 |  0.0000 | daily sustenance
     8 | alice        | 1.0000 |        |  1.0001 | total production from land 356a192b7913b0
     8 | alice        |        | 1.0000 |  0.0001 | daily sustenance
     9 | alice        | 1.0001 |        |  1.0002 | total production from land 356a192b7913b0
     9 | alice        |        | 1.0000 |  0.0002 | daily sustenance
     9 | alice        |        | 0.0000 |  0.0002 | spoilage
    10 | alice        | 1.0002 |        |  1.0003 | total production from land 356a192b7913b0
    10 | alice        |        | 1.0000 |  0.0003 | daily sustenance
    10 | alice        |        | 0.0000 |  0.0003 | spoilage
(13 rows)
--------------------------------------------

This report shows that during each click Alice received the
total food production (by virtue of her owning the land)
associated with the particular contract.  Note the trend,
just barely within rounding error, of increasing total food
production at the start of each click.  This increase is a
due to a combination of Alice's improving health, cultivation
proficiency, and the increasing land productivity, as discussed
in the previous tutorials, and results in a food surplus (i.e.,
a net balance of excess food).

The one unit per click deduction for daily sustenance is a
game constant: every 'Fairian' consumes one unit of food
per click, or the net balance if the net balance is less
than one. The consequence of this latter situation (i.e.,
having insufficient food to meet the sustenance requirement)
adversely affects 'Fairian' health and is discussed more fully
in a subsequent tutorial.

The per-click deduction for spoilage is a small constant
percentage calculated on the 'Fairian''s net balance
of food. This ensures that no 'Fairian' can hoard food
indefinitely.

Over time, as cultivation maximizes the land productivity and
Alice's proficiency and health improve, this net surplus will
grow. As the surplus grows, the amount of food spoilage will
accordingly increase until the net surplus growth reaches an
equilibrium point.  Exactly how much food can be maximally
retained and how quickly that maximum is achieved will be
dependent upon the various game parameters randomly determined
at game start up.


== Fairwinds Game Tutorial 9 - Sustenance and the Health Journal

A newly-created 'Fairian' health status is set to the lesser of
100% or the lowest health percentage value of all other players.

Changes to 'Fairian' health are recorded in the health journal.

=== Maintaining Health

Maintaining health requires sustenance (food): during each
click that a 'Fairian' has a food surplus over the amount to
meet the sustenance requirement of one food unit per click,
health improves; during each click that a 'Fairian' has less
than one sustenance unit, health deteriorates. Otherwise,
health status remains unchanged.

=== Health Status Changes

In both the first two cases, the change over time exhibits
diminishing returns behavior in that as improving health
approaches 100%, the per click improvement decreases so that
the balance never exceeds unity. Conversely, diminishing health
is never less than zero so as health decreases, the per-click
amount of atrophy itself decreases.
 

--------------------------------------------
                                                    Health Journal
 click | fairian_name |  debit  | credit  | balance |                           description                           
-------+--------------+---------+---------+---------+-----------------------------------------------------------------
     1 | alice        | 1.00000 |         |   1.000 | Initial health
     2 | alice        |         | 0.01964 |   0.980 | health deterioration based on insufficient sustenance balance 0
     3 | alice        |         | 0.01925 |   0.961 | health deterioration based on insufficient sustenance balance 0
     4 | alice        |         | 0.01887 |   0.942 | health deterioration based on insufficient sustenance balance 0
     5 | alice        |         | 0.01850 |   0.924 | health deterioration based on insufficient sustenance balance 0
     7 | alice        | 0.00150 |         |   0.925 | health improvement based on sustenance balance 1.000012
     8 | alice        | 0.00147 |         |   0.927 | health improvement based on sustenance balance 1.000058
     9 | alice        | 0.00144 |         |   0.928 | health improvement based on sustenance balance 1.000161
    10 | alice        | 0.00141 |         |   0.930 | health improvement based on sustenance balance 1.000341
(9 rows)
--------------------------------------------

This report shows that:

* At click 1, when Alice entered the game, she was endowed with perfect health (100%).
* Alice's health immediately began atrophying by a small percentage each click since she had no food.
* Recovery started once she began producing food through cultivation.

The transition to improving health corresponds to when Alice
began her engagement in cultivation and thereby satisfied
the periodic sustenance requirement. Note further that the
per-click health atrophy decreases by a continually smaller
amount as her net health atophies.

Conversely, during recovery, health improves by continually
decreasing amounts.

And lastly note in the description column annotates these
effects.


The rate of health improvement and deterioration are small
percentage constants fixed when the game is initialized.

Note that a 'Fairian'''s' net health value influences their
ability to perform skilled tasks, 'e.g.', a 'Fairian'''s'
'effectiveness' is adversely affected by poor health and
decreases their food production.

=== Stationary Zero Health Status

The third case, 'i.e.', when a 'Fairian' enters a click with
exactly one food unit, results in no change to health status. In
the particular circumstance of zero health and being a sole
cultivator of a land plot, health status remains at zero since
zero health results in zero cultivation effectiveness so there
is no food surplus generated.

=== Emerging from Stationary Zero Health Status

There are three ways to emerge from stationary zero health,
and they all involve, as a necessary condition, a food surplus.


[horizontal] 
Buy Food:: Maybe the most straightforward means of emerging
from stationarity is to buy food. This works, of course,
only if other 'Fairians' have generated a food surplus and
are willing to sell some.

Sell Labor:: Another means is to hire on as a supplier on the
labor market.  Provided that the work site is being cultivated
by at least one other 'Fairian' with non-zero effectiveness,
you will share in the fruits of the combined team effectiveness
and get a share of the excess production.

Buy Labor:: Similar to hiring out as a supplier as above, you
can alternatively hire another 'Fairian' to jointly cultivate a
land plot you own. Provided they have non-zero effectiveness,
you will similarly share in the fruits of the combined team
effectiveness.





== Fairwinds Game Tutorial A - We Have Company

At this point we introduce a second player, Bob. Bob goes through
similar initial steps as Alice creating an account and runs the 
Player report:

--------------------------------------------
                                               Fairians
 fairian_name |  email_address  |        created_date        | click_order_count | click_select_count 
--------------+-----------------+----------------------------+-------------------+--------------------
 alice        |                 | 2015-12-17 12:17:23.156867 |                 0 |                  0
 bob          | bob@example.com | 2015-12-17 19:25:54.064911 |                 0 |                  0
(2 rows)
--------------------------------------------

Note that upon listing other players, the system does not allow Bob to
see the email address of other registered players, only his own.


Then he places a market bid order with default values to bootstrap
the land market. The game standings web page shows the newly
surveyed land offered for sale:

--------------------------------------------
                                  Land Asks
 serial_number  | expiration | productivity |  price   | fairian_name | side 
----------------+------------+--------------+----------+--------------+------
 77de68daecd823 |            |      0.00000 | 0.534242 |              | ask
(1 row)
--------------------------------------------


At this point, Bob's experience differs from that of Alice earlier:
This second land plot, rather than being given away free, has a non-zero
price according to the virgin land scarcity pricing algorithm, so Bob 
needs cash.


== Fairwinds Game Tutorial B - Bootstrapping the Bond Market

As described earlier, when 'Fairwinds' is initialized, there
are no 'Fairians', no land, no food, and no money.  As players
enter the game, resources must be brought into existence by
means of market activity that creates demand.  We have already
seen bootstrapping the land market. Bootstrapping money happens
on the bond market.

This tutorial illustrates the bootstrapping protocol for the
bond market.

Bob invokes the fairbot menu script and selects the Trading
menu item for a bond ask order:

--------------------------------------------
1) Create     - Create a Fairian account named bob
2) Reports    - Display game data
3) Trade      - Enter buy/sell orders
4) Labor      - Assign self-owned labor contract
5) Terminate  - End a labor contract
6) Call       - Demand note payment
Main menu selection 3

1) bond
2) land
3) work
4) food
5) note
Select market 1

1) bid - Buy order
2) ask - Sell order
bond buy or sell? 2

expiration=
ask price=
bond term=
--------------------------------------------

+Expiration+ is the same as for other markets, specifying how
long the order will stand open for before expiration. Defaults
to one.

+Price+ in the case of a bond sell order is the minumum loan
amount the bond issuer asks to borrow. Unspecified implies a
market order, i.e., the available bid price.

+Term+ is the minimum amount of time in clicks the borrow
wants before repayment is required.

Bob borrows money by issuing ('i.e.', selling) a bond, that
is, he makes a promise to repay a fixed amount at some future
time. 'Fairian' bonds always have a face value of fc1000
(1000 'Faircoin') and trade at a discount from this. That
is, in 'Fairwinds', bonds are more similar to real-world
Treasury Bills, having no coupon, than to Treasury Bonds
('i.e.' real-world bonds pay periodic interest as well as
derive value by discount trading; 'Fairwinds' bonds employ the
discount mechanism only). An effective interest rate is implied
by the discount from face value and the term length to maturity.

For the case of bootstrapping, none of the trade parameter
value entries are required.

The default values effectively specify a market order selling a
bond with a term of one click, but, as with bootstrapping the
land market, since there were no open orders on the opposite
side, the sell order is not recorded in the order book but
rather triggers the governing market authority to create a
bond buy order.

The price for this bootstrapped buy order is not discounted,
'i.e.', bootstrapped bond buy orders are offered at zero
effective interest rate. Note also though, that it is a very
short-term maturity. The implication here is that when no other
'Fairians' are willing to lend money ('i.e.', to buy bonds),
then the game will create money and lend it short term for free.
This provides a degree of liquidity, making it possible for new
players to buy a land plot or initiate other economic activity.

As with the land bootstrapping protocol, the 'Fairian' who
triggers demand invoking the bootstrapping protocol has no
special right to the proceeds. The bootstrapped bond bid order
will be matched against the best of any 'Fairians' open bond
issue sell order.

Bob (re-)places his bond market ask order in order to complete
his loan execution and confirms that the bond has been issued
by examining the game standings web site:

--------------------------------------------
                                    Bonds
 serial_number  | issue_date | term | face_amount | bond_owner | bond_issuer 
----------------+------------+------+-------------+------------+-------------
 1b6453892473a4 |         11 |    2 |        1000 |            | bob
(1 row)
--------------------------------------------


Bob has borrowed fc1000 of cash created by the governing market
authority, which he can see in his cash journal

--------------------------------------------
                         Recent Cash Journal Entries
 click | fairian_name | debit | credit | balance |        description         
-------+--------------+-------+--------+---------+----------------------------
    10 | bob          |     0 |      0 |       0 | Initial cash balance
    11 | bob          |  1000 |        |    1000 | Issued bond 1b6453892473a4
(2 rows)
--------------------------------------------

which lists Bob's inital zero cash balance and the bond issue 
loan proceeds.



=== Deploying Bond Proceeds

Now that Bob has cash, he can proceed to buy the land plot, so 
he (re-)places his land market order to buy and then confirms 
that he is now the owner of land plot \'77de68daecd823':

--------------------------------------------
                        Land Plots
 fairian_name | serial_number  | productivity | land_value 
--------------+----------------+--------------+------------
 alice        | 356a192b7913b0 |      0.00506 |      0.534
 bob          | 77de68daecd823 |      0.00000 |      0.534
(2 rows)
--------------------------------------------

Note the +land_value+ entry. Land value is adjusted whenever
a land trade executes. The executed trade is taken to set
the value of the subject plot and all others according to
productivity values. Any land with greater productivity than
the subject plot are set to be at least as valuable as the
traded plot value, and plots with lesser productivity are set
to value no more than the traded plot value.

As this market activity occurs, the net wealth of 'Fairians'
as listed in the standings report will be adjusted accordingly.

Once Bob succeeds in buying the land plot, he proceeds similarly
to as Alice did and creates a self-owned land labor contract
and commences cultivation and then checks the status of
existing labor contracts. As expected he sees his own, newly
established labor contract listed as well as the earlier one
involving Alice on her land:

--------------------------------------------
                                           Labor Contracts
   work_place   | skill_name | contract_number | issue_date | term | customer | supplier | labor_rate 
----------------+------------+-----------------+------------+------+----------+----------+------------
 356a192b7913b0 | farmer     | da4b9237bacccd  |          5 |    1 | alice    | alice    |      0.000
 77de68daecd823 | farmer     | ac3478d69a3c81  |         12 |    1 | bob      | bob      |      0.000
(2 rows)
--------------------------------------------


== Fairwinds Game Tutorial C - The Cash Journal

The cash_journal records transactions involving Faircoin. For 
example, all executed buy and sell transactions, bond issues 
and redemptions, etc., are recorded:

--------------------------------------------
                                         Cash Journal
 click | fairian_name | account |  debit   | credit  | balance  |         description          
-------+--------------+---------+----------+---------+----------+------------------------------
     1 | alice        | cash    |    0.000 |   0.000 |    0.000 | Initial cash balance
     4 | alice        | land    |          |   0.000 |    0.000 | Bought land 356a192b7913b0
    10 | bob          | cash    |    0.000 |   0.000 |    0.000 | Initial cash balance
    11 | bob          | bond    | 1000.000 |         | 1000.000 | Issued bond 1b6453892473a4
    12 | bob          | land    |          |   0.534 |  999.466 | Bought land 77de68daecd823
    13 | bob          | bond    |          | 999.466 |    0.000 | Redeemed bond 1b6453892473a4
(6 rows)
--------------------------------------------

This listing shows the initial zero balance for players as they 
entered the game, the zero-cost land purchase by Alice, and then
several transactions by Bob. First is the
distribution to Bob of the loan proceeds of him issuing a 
bond, then the land purchase is listed next, followed
by the matured bond. Since Bob spent some of the money on land, 
he did not have sufficient funds to fully repay the loan.

Note that, from the lenders perspective Bob's cash shortfall is irrelevant:
Bonds are guaranteed investments as far as the lender is concerned. The
governing market authority creates enough Faircoin to fully repay the lender
at bond maturity.

But Bob does not necessarily get let off the hook for the cash shortfall.



== Fairwinds Game Tutorial D - The Debt Market

In the previous tutorial, Bob was short of cash to repay a bond
he issued.  When this happens, a demand note is issued listing
Bob as a debtor for the amount of the shortfall. Demand notes
are a mechanism for factoring ('i.e.', re-selling) debt. The
factor ('i.e.', the owner) of a note incurs the right to call
the debt at any time. Any cash the debtor has at the time
of call, up to the note face amount, is relinquished by the
debtor and transferred to the factor.

Demand notes are traded somewhat similarly to bonds in that they
are purchased at a discount from "face value".  Face value in
this case is the corresponding bond redemption shortfall amount.

Note however that there is no secondary market for notes. They
are sold by the governing market authority once, and the buyer
has no mechanism to resell (in contrast to as is the case,
for example, with the real estate or commodity markets for
land or food).

For Bob's case the shortfall is equal to the cost of the
purchased land plot and listed in a report of demand notes:


--------------------------------------------
                         Notes
 serial_number  | issue_date | amount | factor | debtor 
----------------+------------+--------+--------+--------
 c1dfd96eea8cc2 |         23 |  0.534 |        | bob
(1 row)
--------------------------------------------

The +serial_number+ serves as a unique identifier and is
automatically assigned when the note is created.

The +issue_date+ is automatically set for a future click. This
allows for other players to discover the bidding opportunity
and consider how much, if at all, they want to bid on the debt.

When game time advances to the issue_date click, a market sell
order is added to the note_ask table and is automatically
matched against any open limit buy orders for that specific
note serial number: the highest bid amount trade executes and
the others are expired on the subsequent click. If there are
no open bid orders for a specific note at issue time, then
the note order is changed from a market order to a limit order
with price zero.

The 'factor' of a note is equivalent to the owner of a bond,
and calling a note is something like redemption at maturity
of a bond. Upon demand note redemption, cash is transferred
from the debtor to the factor, provided the debtor has cash
when the note is called.

Demand notes are redeemed by calling them, which is action on
the +fairbot+ main menu. Calling a note is literally a demand
for payment.

A demand note can be called only once, after which it is
expired and no longer listed in the note view nor accessible
to the factor or other players.

Alice proceeds to place a buy order for the note.  (This
particular case is not very lucrative, but it serves to
illustrate the process.)

--------------------------------------------
1) Create     - Create a Fairian account named alice
2) Reports    - Display game data
3) Trade      - Enter buy/sell orders
4) Labor      - Assign self-owned labor contract
5) Terminate  - End a labor contract
6) Call       - Demand note payment
Main menu selection 3

1) bond
2) land
3) work
4) food
5) note
Select market 5

1) bid - Buy order
2) ask - Sell order
note buy or sell? 1

expiration=10
bid price=0
1) c1dfd96eea8cc2
Select note serial number 1
--------------------------------------------

The serial_number is essential and must be specified
since a note bid is made for specific notes individually.
The expiration, if not specified, defaults to one, but generally
should be long enough to last until the future note issue date.

Since Alice knows she is the only bidder, she "low-balls"
by making a bid for zero Faircoin and confirms her entry by
examining the note bids listed on the game standings web site:

--------------------------------------------
                     Note Bids
 serial_number  | expiration | price | fairian_name 
----------------+------------+-------+--------------
 c1dfd96eea8cc2 |         24 | 0.000 | alice
(1 row)
--------------------------------------------


Ten clicks later, when the note is actually sold, Alice's bid
"wins" and she becomes the note owner (factor):

--------------------------------------------
                         Notes
 serial_number  | issue_date | amount | factor | debtor 
----------------+------------+--------+--------+--------
 c1dfd96eea8cc2 |         23 |  0.534 | alice  | bob
(1 row)
--------------------------------------------


Although it makes little sense for Alice to do so now, since
Bob has no cash, for purposes of illustration we show how
Alice would call the note:

--------------------------------------------
1) Create     - Create a Fairian account named alice
2) Reports    - Display game data
3) Trade      - Enter buy/sell orders
4) Labor      - Assign self-owned labor contract
5) Terminate  - End a labor contract
6) Call       - Demand note payment
Main menu selection 6

1) c1dfd96eea8cc2
Select note serial number 1
--------------------------------------------

The effect of the demand is evident in the cash journal
report that now includes the collection activity, which
was unsuccessful since Bob the debtor was indigent at time
of demand.


--------------------------------------------
                                                  Cash Journal
 click | fairian_name | account |  debit   | credit  | balance  |                  description                  
-------+--------------+---------+----------+---------+----------+-----------------------------------------------
     1 | alice        | cash    |    0.000 |   0.000 |    0.000 | Initial cash balance
     4 | alice        | land    |          |   0.000 |    0.000 | Bought land 356a192b7913b0
    10 | bob          | cash    |    0.000 |   0.000 |    0.000 | Initial cash balance
    11 | bob          | bond    | 1000.000 |         | 1000.000 | Issued bond 1b6453892473a4
    12 | bob          | land    |          |   0.534 |  999.466 | Bought land 77de68daecd823
    13 | bob          | bond    |          | 999.466 |    0.000 | Redeemed bond 1b6453892473a4
    23 | alice        | note    |          |   0.000 |    0.000 | Bought note c1dfd96eea8cc2
    24 | bob          | note    |          |   0.000 |    0.000 | Collection c1dfd96eea8cc2: Debtor is indigent
    24 | alice        | note    |    0.000 |         |    0.000 | Collection c1dfd96eea8cc2: Debtor is indigent
(9 rows)
--------------------------------------------


== Fairwinds Game Tutorial E - Hiring Labor

Check back later for more updates!!!
